#pragma once
#include "../src/config.h"

// composite では UART ミラーは使わない
#undef MIDI_UART_MIRROR_ENABLE
#define MIDI_UART_MIRROR_ENABLE 0

// RESET / SUSTAIN を統合 — composite では GP28/GP29 (MUTE/LYRE) と衝突するため 26/27 に分離
#ifndef COMPOSITE_RESET_PIN
#define COMPOSITE_RESET_PIN 26
#endif
#ifndef COMPOSITE_SUSTAIN_PIN
#define COMPOSITE_SUSTAIN_PIN 27
#endif

#ifndef COMPOSITE_RESET_ENABLE
#define COMPOSITE_RESET_ENABLE 1
#endif
#ifndef COMPOSITE_SUSTAIN_ENABLE
#define COMPOSITE_SUSTAIN_ENABLE 1
#endif

#ifndef COMPOSITE_RESET_ACTIVE_LEVEL
#define COMPOSITE_RESET_ACTIVE_LEVEL 0
#endif
#ifndef COMPOSITE_RESET_DEBOUNCE_MS
#define COMPOSITE_RESET_DEBOUNCE_MS 20
#endif
#ifndef COMPOSITE_SUSTAIN_ACTIVE_LEVEL
#define COMPOSITE_SUSTAIN_ACTIVE_LEVEL 0
#endif
#ifndef COMPOSITE_SUSTAIN_DEBOUNCE_MS
#define COMPOSITE_SUSTAIN_DEBOUNCE_MS COMPOSITE_RESET_DEBOUNCE_MS
#endif
#ifndef COMPOSITE_SUSTAIN_MIDI_CHANNEL
#define COMPOSITE_SUSTAIN_MIDI_CHANNEL 0
#endif
